const temario = 
[
    "1. Representación y comunicación de la información."
    ,"2. Elementos funcionales de un ordenador digital."
    ,"3. Componentes, estructura y funcionamiento de la Unidad Central de Proceso."
    ,"4. Memoria interna. Tipos. Direccionamiento. Características y funciones."
    ,"5. Microprocesadores. Estructura. Tipos. Comunicación con el exterior."
    ,"6. Sistemas de almacenamiento externo. Tipos. Características y funcionamiento."
    ,"7. Dispositivos periféricos de entrada/salida. Características y funcionamiento."
    ,"8. 'Hardware' comercial de un ordenador. Placa base. Tarjetas controladoras de dispositivos y de entrada/salida."
,"9. Lógica de circuitos. Circuitos combinacionales y secuenciales."
,"10. Representación interna de los datos."
,"11. Organización lógica de los datos. Estructuras estáticas."
,"12. Organización lógica de los datos. Estructuras dinámicas."
,"13. Ficheros. Tipos. Características. Organizaciones."
,"14. Utilización de ficheros según su organización."
,"15. Sistemas operativos. Componentes. Estructura. Funciones. Tipos."
,"16.Sistemas operativos: Gestión de procesos."
,"17. Sistemas operativos. Gestión de memoria."
,"18. Sistemas operativos: Gestión de entradas/salidas."
,"19. Sistemas operativos: Gestión de archivos y dispositivos."
,"20. Explotación y Administración de sistemas operativos monousuario y multiusuario."
,"21. Sistemas informáticos. Estructura física y funcional."
,"22. Planificación y explotación de sistemas informáticos. Configuración. Condiciones de instalación. Medidas de seguridad. Procedimientos de uso."
,"23. Diseño de algoritmos. Técnicas descriptivas."
,"24. Lenguajes de programación. Tipos. Características."
,"25. Programación estructurada. Estructuras básicas. Funciones y Procedimientos."
,"26. Programación modular. Diseño de funciones. Recursividad. Librerías."
,"27. Programación orientada a objetos. Objetos. Clases. Herencia. Polimorfismo. Lenguajes."
,"28. Programación en tiempo real. Interrupciones. Sincronización y comunicación entre tareas. Lenguajes."
,"29. Utilidades para el desarrollo y prueba de programas. Compiladores. Intérpretes. Depuradores."
,"30. Prueba y documentación de programas. Técnicas."
,"31. Lenguaje C: Características generales. Elementos del lenguaje. Estructura de un programa. Funciones de librería y usuario. Entorno de compilación. Herramientas para la elaboración y depuración de programas en lenguaje C."
,"32. Lenguaje C: Manipulación de estructuradas de datos dinámicas y estáticas. Entrada y salida de datos. Gestión de punteros. Punteros a funciones."
,"33. Programación en lenguaje ensamblador. Instrucciones básicas. Formatos. Direccionamientos."
,"34. Sistemas gestores de base de datos. Funciones. Componentes. Arquitecturas de referencia y operacionales. Tipos de sistemas."
,"35. La definición de datos. Niveles de descripción. Lenguajes. Diccionario de datos."
,"36. La manipulación de datos. Operaciones. Lenguajes. Optimización de consultas."
,"37. Modelo de datos jerárquico y en red. Estructuras. Operaciones."
,"38. Modelo de datos relacional. Estructuras. Operaciones. Álgebra relacional."
,"39. Lenguajes para la definición y manipulación de datos en sistemas de base de datos relacionales. Tipos. Características. Lenguaje SQL."
,"40. Diseño de bases de datos relacionales."
,"41. Utilidades de los sistemas gestores de base de datos para el desarrollo de aplicaciones. Tipos. Características."
,"42. Sistemas de base de datos distribuidos."
,"43. Administración de sistemas de base de datos."
,"44. Técnicas y procedimientos para la seguridad de los datos."
,"45. Sistemas de información. Tipos. Características. Sistemas de información en la empresa."
,"46. Aplicaciones informáticas de propósito general y para la gestión empresarial. Tipos. Funciones. Características."
,"47. Instalación y explotación de aplicaciones informáticas. Compartición de datos."
,"48. Ingeniería del 'software'. Ciclo de desarrollo del 'software'. Tipos de ciclos de desarrollo. Metodologías de desarrollo. Características distintivas de las principales metodologías de desarrollo utilizadas en la Unión Europea."
,"49. Análisis de sistemas: Modelización de tratamientos. Modelo de flujo de datos y control. Técnicas descriptivas. Documentación."
,"50. Análisis de sistemas: Modelización conceptual de datos. Técnicas descriptivas. Documentación."
,"51. Análisis de sistemas: Especificación funcional del sistema. Búsqueda y descripción de requisitos funcionales. Especificación de soluciones técnicas. Análisis de viabilidad técnica y económica."
,"52. Diseño lógico de funciones. Definición de funciones. Descomposición modular. Técnicas descriptivas. Documentación."
,"53. Diseño lógico de datos. Transformación del modelo conceptual a modelos lógicos. Análisis relacional de datos. Documentación."
,"54. Diseño de interfaces de usuario. Criterios de diseño. Descripción de interfaces. Documentación. Herramientas para la construcción de interfaces."
,"55. Diseño físico de datos y funciones. Criterios de diseño. Documentación."
,"56. Análisis y diseño orientado a objetos."
,"57. Calidad del 'software'. Factores y métricas. Estrategias de prueba."
,"58. Ayudas automatizadas para el desarrollo de 'software' (herramientas CASE). Tipos. Estructura. Prestaciones."
,"59. Gestión y control de proyectos informáticos. Estimación de recursos. Planificación temporal y organizativa. Seguimiento."
,"60. Sistemas basados en el conocimiento. Representación del conocimiento. Componentes y arquitectura."
,"61. Redes y servicios de comunicación."
,"62. Arquitecturas de sistemas de comunicaciones. Arquitecturas basadas en niveles. Estándares."
,"63. Funciones y servicios del nivel físico. Tipos y medios de transmisión. Adaptación al medio de transmisión. Limitaciones a la transmisión. Estándares."
,"64. Funciones y servicios del nivel de enlace. Técnicas. Protocolos."
,"65. Funciones y servicios del nivel de red y del nivel de transporte. Técnicas. Protocolos."
,"66. Funciones y servicios en niveles sesión, presentación y aplicación. Protocolos. Estándares."
,"67. Redes de área local. Componentes. Tipologías. Estándares. Protocolos."
,"68. 'Software' de sistemas en red. Componentes. Funciones. Estructura."
,"69. Integración de sistemas. Medios de interconexión. Estándares. Protocolos de acceso a redes de área extensa."
,"70. Diseño de sistemas en red local. Parámetros de diseño. Instalación y configuración de sistemas "
,"en red local."
,"71. Explotación y administración de sistemas en red local. Facilidades de gestión."
,"72. La seguridad en sistemas en red. Servicios de seguridad. Técnicas y sistemas de protección. Estándares."
,"73. Evaluación y mejora de prestaciones en un sistema en red. Técnicas y procedimientos de medidas."
,"74. Sistemas multimedia"
]